### PR TITLE
change to smaller and signed comp desctiptor

### PR DESCRIPTION
**Pull request by morrison-sap**
## Description

add new signature algorithm and change to smaller comp descriptor.

### CODE REVIEW

**Review by n-boshnakov — APPROVED** [review]
While I can't attest to the correctness of the code, the documentation changes look fine to me.

**Comment by Skarlso** [comment]
Well, I didn't want to use an outside package, so I wanted to rather create a new one and sign in. 🤷 But this works too I guess.

**Comment by morri-son** [comment]
> Well, I didn't want to use an outside package, so I wanted to rather create a new one and sign in. 🤷 But this works too I guess.

? I stumbled upon the first sentence which speaks of a signed component and just checked what the comp looked before and copied it from an older version. Wasn't this ok? Does this introduce any issues and we should change it?

**Comment by Skarlso** [comment]
Yes, the original uses weave-gitops and Piaras's own component. I was going to create one under open-component-model and sign that and use that as an example.

**Comment by morri-son** [comment]
@Skarlso: Another idea would be to use the component ocm.software/ocmcli:0.11.0 (or whatever) on ghcr.io/open-component-model/ocm. This component version is created during every release and I guess is uses

https://github.com/open-component-model/ocm/blob/main/components/ocmcli/Makefile

Maybe we simply add a signing step here and use this component instead of creating one that we can use in the documentation? @Skarlso @mandelsoft , what do you think?

**Comment by Skarlso** [comment]
Yep, that works for me.

**Pull request merged**
