### PR TITLE
fix: remove the restriction on commands to document

### PR DESCRIPTION
**Pull request by Skarlso**
## Description

https://github.com/open-component-model/ocm-project/issues/166

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Skarlso** [comment]
@mandelsoft Please provide some input as to the usefulness of these commands being on the website. They contain a lot of information that seems to be either very specific to a specific usecase or not relevant to most of the end-users.

**Comment by morri-son** [comment]
@mandelsoft to be a bit more specific. In the current implementation there was a whitelist for commands to be synced to the website. Just doing a dumb sync seems to pull things that we don't won't to show at all or at least would like to introduce a structure with folders or groups that sort the commands and other help topics in a better way. So, it is about where do we want to introduce such a grouping? I still think that it would be a good idea to be able to do a 1:1 copy of all help topics to the website. To be able to do that we need to do a clean-up of the help topics in the ocm repo. And until this is ready, we would require the whitelist that exists on the website already and add the things we think make sense to be synced.

What do you think about getting the help resources / markdown files into a shape that can be copied 1:1 to the website without overwhelming the end user with commands that are of lower importance?

**Comment by mandelsoft** [comment]
Sure, the best solution would be a 1:1 copy. But I'm not sure, where the problem is. The generated docu is self contained.

If you want to omit some commands, this would always lead to danglings links.
So, the only way would be to re-generate the reference docu for dedicated use cases.

The renderer could be extended to accept a list of commands, which should be omitted.
Or what do you think, should be the solution?

**Comment by Skarlso** [comment]
The question is rather about the content. How relevant these commands are or if we should even show them.

Such as `ocm ocm toi` or `ocm ocm routingslips add` which are either very specific to something or just plain confusing to look at. :)

**Comment by mandelsoft** [comment]
I would separate the tree view on the left side from the copied reference (1:1 as is )

On the left side we have  structured entry points:

- ocm command (the main command) -> link to the main command ref page
- help topics
  - <list of all help topis>  -> link to the dedicated help topic page
- sub commands
  - <list of verbs> -> link to dedicated sub command page

**Comment by morri-son** [comment]
HI @Skarlso Uwe's proposal sounds reasonable. For the help topics we use 

```
Additional help topics:
  ocm attributes           configuration attributes used to control the behaviour
  ocm configfile           configuration file
  ocm credential-handling  Provisioning of credentials for credential consumers
  ocm logging              Configured logging keys
  ocm oci-references       notation for OCI references
  ocm ocm-accessmethods    List of all supported access methods
  ocm ocm-downloadhandlers List of all available download handlers
  ocm ocm-labels           Labels and Label Merging
  ocm ocm-references       notation for OCM references
  ocm ocm-uploadhandlers   List of all available upload handlers
  ocm toi-bootstrapping    Tiny OCM Installer based on component versions
```

Instead of an allow list for the sub commands Hilmar proposed a deny list. It's shorter and if someone adds something new it will be added automatically until added to the deny list. From the list of available sub commands

```
Available Commands:
  add                  Add elements to a component repository or component version
  bootstrap            bootstrap components
  cache                Cache related commands
  check                check components in OCM repository
  clean                Cleanup/re-organize elements
  completion           Generate the autocompletion script for the specified shell
  controller           Commands acting on the ocm-controller
  create               Create transport or component archive
  credentials          Commands acting on credentials
  describe             Describe various elements by using appropriate sub commands.
  download             Download oci artifacts, resources or complete components
  execute              Execute an element.
  get                  Get information about artifacts and components
  hash                 Hash and normalization operations
  help                 Help about any command
  install              Install elements.
  oci                  Dedicated command flavors for the OCI layer
  ocm                  Dedicated command flavors for the Open Component Model
  show                 Show tags or versions
  sign                 Sign components or hashes
  toi                  Dedicated command flavors for the TOI layer
  transfer             Transfer artifacts or components
  verify               Verify component version signatures
  version              displays the version
```

I propose to add the following to the deny list:

```
bootstrap
cache
completion
controller
credentials
execute
hash
help
install
oci
ocm
toi
version
```

**Comment by Skarlso** [comment]
Closing in favour of https://github.com/open-component-model/ocm-website/pull/219

**Pull request closed without merging**
